### ISSUE TITLE
kedr/config.h:104:12: error: ‘struct module’ has no member named ‘module_core’   return mod->module_core

### ISSUE THREAD

**Issue by fanwaken** [euspectre/kedr#40]
cmake succeed
make errors (any plan to support newer kernels)

Linux sender1 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by euspectre** [comment]
Will take a look, thanks.

**Comment by euspectre** [comment]
Hm. Which version of KEDR are you trying to build and how did you configure it with CMake?

I have re-checked that the current sources from git repo (v0.6) build just fine on kernel 4.8.7. Haven't tried the Ubuntu kernels though.

**Comment by vinayvarahabhotla** [comment]
Can you please try this in ubuntu xenial because even I am getting the same error as above

**Comment by euspectre** [comment]
Will take a look, but first of all, which version of KEDR are you trying to build there?

**Comment by vinayvarahabhotla** [comment]
Hello,
I am using the following sources:
KEDR version : 0.6
Kernel Version : 4.4.24
Ubuntu : Xenial

**Comment by euspectre** [comment]
I suppose you mean 4.4.0-24 because there is no stock 4.4.24 kernel in Ubuntu. The 4.4.0-24 and 4.4.24 kernels are *very* different inside.

Looks like they backported the changes from the newer kernels and broke things again, sigh.

**Comment by euspectre** [comment]
Should be fixed by https://github.com/euspectre/kedr/commit/25552044f22781e21ee4ccc9ea044dd8dc58f59d.

Just to make it clear, for the future: if you see KEDR does not build or breaks on some distribution-specific kernel, your patches are welcome.

I manage to find some time to maintain KEDR 0.x for the kernels from kernel.org, but not always for the distro-specific kernels.
